version: '2'

volumes:
    nginx-conf:
    nginx-log:
    j2-static:
    j2-media:
    

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
        - "8080:80"
        volumes:
        - nginx-conf:/etc/nginx/conf.d
        - nginx-log:/var/log/nginx
        - j2-static:/app/jinja2parser/static
        - j2-media:/app/jinja2parser/media
    web:
        image: rdtayloruk/jinja2parser:0.1
        container_name: jinja2parser
        environment:
        - DJANGO_SECRET_KEY=tcpip123
        - DJANGO_DEBUG=False
        - DJANGO_LOGLEVEL=INFO
        volumes:
        - j2-static:/app/static
        - j2-media:/app/media
        
        expose:
        - "8000"
        depends_on:
        - nginx
