version: '2'

volumes:
    j2p-static:
    j2p-media:

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
        - "8080:80"
        volumes:
        - j2p-static:/app/jinja2parser/static
        - j2p-media:/app/jinja2parser/media
    web:
        image: rdtayloruk/jinja2parser:0.1
        container_name: jinja2parser
        environment:
        - DJANGO_SECRET_KEY=tcpip123
        - DJANGO_DEBUG=False
        - DJANGO_LOGLEVEL=INFO
        volumes:
        - j2p-static:/app/static
        - j2p-media:/app/media
        expose:
        - "8000"
        depends_on:
        - nginx
